Added a check for the password column in the mysql.user table to accomodate older mysql hosts, also fix the port discovery from the mysql_inventory table, and port export in docker for proxysql to be 3306

diff --git a/mysql-proxy-credential-sync b/mysql-proxy-credential-sync
--- a/mysql-proxy-credential-sync
+++ b/mysql-proxy-credential-sync
@@ -27,6 +27,28 @@ db_connection(){
     done
 }
 
+get_password_column_name(){
+	column_name=''
+	host=''
+
+	if [ $1 ]; then
+		host="-h$1"
+	fi 
+	if [ `mysql --login-path=$MYSQL_USER_CONFIG $host -e "SELECT authentication_string FROM mysql.user" > /dev/null 2>&1; echo $?` -eq 0 ]; then
+		column_name='authentication_string'
+	fi
+	if [ `mysql --login-path=$MYSQL_USER_CONFIG $host -e "SELECT password FROM mysql.user" > /dev/null 2>&1; echo $?` -eq 0 ]; then
+		column_name='password'
+	fi
+
+	if [ "$column_name" == "" ]; then
+		echo "Unable to determine the password column for the mysql.user table"
+	fi
+
+	echo $column_name
+}
+
+
 while true; do
     # Validate database connectivity
     db_connection
@@ -35,9 +57,9 @@ while true; do
     # Will only ne working on credentials that start with v-ldap and are vault created credentials.  This script will not touch any other logins.
     OLD_IFS=$IFS
     IFS=$'\n'
-
-    VAULT_USER_RESULT=($(mysql --login-path=$MYSQL_USER_CONFIG -Bse "SELECT Host,User,authentication_string,Select_priv,Insert_priv FROM mysql.user WHERE TIMESTAMPDIFF(HOUR, password_last_changed, NOW()) < 24 AND user LIKE '$MYSQL_USER_PREFIX%'"))
-    echo "Discovering the vault users from the MySQL instance"
+    echo "Discovering the vault users from the MySQL instance"	
+    PASS_COL=`get_password_column_name`
+    VAULT_USER_RESULT=($(mysql --login-path=$MYSQL_USER_CONFIG -Bse "SELECT Host,User,$PASS_COL,Select_priv,Insert_priv FROM mysql.user WHERE TIMESTAMPDIFF(HOUR, password_last_changed, NOW()) < 24 AND user LIKE '$MYSQL_USER_PREFIX%'"))
     for i in ${VAULT_USER_RESULT[@]}; do
         host=`echo $i | awk '{print $1}'`
         user=`echo $i | awk '{print $2}'`
@@ -69,8 +91,9 @@ while true; do
 		if [ $? -ne 0 ] || [ $enabled -eq 0 ] ;then
 			echo "  Failed to connect to $ihost or it's disabled : $enabled"
 		else
-			echo "  Starting sync on $ihost"
-			HOST_USER_RESULT=($(mysql --login-path=$MYSQL_USER_CONFIG -h $ip -P $port -Bse "SELECT user,password FROM mysql.user WHERE user LIKE '$MYSQL_USER_PREFIX%'"))
+			echo "  Starting sync on $ip"
+			PASS_COL=`get_password_column_name $ip`
+			HOST_USER_RESULT=($(mysql --login-path=$MYSQL_USER_CONFIG -h $ip -P $port -Bse "SELECT user,$PASS_COL FROM mysql.user WHERE user LIKE '$MYSQL_USER_PREFIX%'"))
 			echo "    Sync and remove old stale credentials"
 			for hu in ${HOST_USER_RESULT[@]}; do
 				host_user=`echo $hu | awk '{print $1}'`
@@ -189,7 +212,10 @@ while true; do
 		if [ ! $host_ip ]; then
 			echo "      No IP found for $vault_host in the host or ip field of the table.  Please check the mysql_inventory to ensure your hosts/ip match the hostname or ip configured in your vault policies."
 		else
-			host_port=`mysql --login-path=$MYSQL_USER_CONFIG mysql_inventory -Bse "select port from hosts where host='$vault_host';"`
+			host_port=`mysql --login-path=$MYSQL_USER_CONFIG mysql_inventory -Bse "select port from hosts where host='$vault_host' OR ip='$vault_host';"`
+			if [ ${#host_port} -eq 0 ]; then
+				host_port=3306
+			fi
 			echo "      Discovered IP $host_ip for host $vault_host"
 			echo "      Checking if there is a host group for this host. First Get the IP, and then Check"
 			host_group_id=`mysql --login-path=$PROXY_USER_CONFIG -Bse "select hostgroup_id from mysql_servers WHERE hostname = '$host_ip';"`
